import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Send, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

interface ChatInputProps {
  onSend: (message: string) => void
  isStreaming: boolean
}

export function ChatInput({ onSend, isStreaming }: ChatInputProps) {
  const [input, setInput] = useState('')

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isStreaming) return
    onSend(input)
    setInput('')
  }

  return (
    <div className="border-t border-border/60 bg-card/90 p-4 backdrop-blur">
      <form
        onSubmit={handleSubmit}
        className="flex items-center gap-2 rounded-full border border-input/70 bg-background px-2.5 py-2.5 shadow-sm transition-shadow focus-within:ring-2 focus-within:ring-primary/20 focus-within:ring-offset-0"
      >
        <Input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask anything about your documents..."
          className="flex-1 border-0 bg-transparent px-4 shadow-none focus-visible:ring-0 focus-visible:ring-offset-0"
          disabled={isStreaming}
        />
        <Button
          type="submit"
          size="icon"
          disabled={!input.trim() || isStreaming}
          className="size-10 shrink-0 rounded-full bg-primary text-primary-foreground shadow-[0_10px_24px_rgba(157,116,116,0.24)] transition-transform hover:bg-primary/90 active:scale-95"
        >
          <AnimatePresence mode="popLayout" initial={false}>
            {isStreaming ? (
              <motion.span
                key="loading"
                initial={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0, opacity: 0 }}
                className="flex items-center justify-center"
              >
                <Loader2 className="size-4 animate-spin" />
              </motion.span>
            ) : (
              <motion.span
                key="send"
                initial={{ scale: 0, opacity: 0, x: -10, y: 10 }}
                animate={{ scale: 1, opacity: 1, x: 0, y: 0 }}
                exit={{ scale: 0, opacity: 0, x: 10, y: -10 }}
                className="flex items-center justify-center"
              >
                <Send className="size-4 ml-0.5" />
              </motion.span>
            )}
          </AnimatePresence>
          <span className="sr-only">Send message</span>
        </Button>
      </form>
      <div className="mt-3 text-center text-xs font-medium text-muted-foreground">
        Responses are generated by AI and may be inaccurate.
      </div>
    </div>
  )
}
