import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Send, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

interface ChatInputProps {
  onSend: (message: string) => void
  isStreaming: boolean
}

export function ChatInput({ onSend, isStreaming }: ChatInputProps) {
  const [input, setInput] = useState('')

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isStreaming) return
    onSend(input)
    setInput('')
  }

  return (
    <div className="p-4 bg-card border-t border-border">
      <form
        onSubmit={handleSubmit}
        className="flex items-center gap-2 rounded-full border border-input bg-background px-2 py-2 focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-0 transition-shadow shadow-sm"
      >
        <Input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask anything about your documents..."
          className="flex-1 border-0 bg-transparent shadow-none focus-visible:ring-0 focus-visible:ring-offset-0 px-4"
          disabled={isStreaming}
        />
        <Button
          type="submit"
          size="icon"
          disabled={!input.trim() || isStreaming}
          className="rounded-full size-10 shrink-0 bg-primary hover:bg-primary/90 text-primary-foreground shadow-sm transition-transform active:scale-95"
        >
          <AnimatePresence mode="popLayout" initial={false}>
            {isStreaming ? (
              <motion.span
                key="loading"
                initial={{ scale: 0, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0, opacity: 0 }}
                className="flex items-center justify-center"
              >
                <Loader2 className="size-4 animate-spin" />
              </motion.span>
            ) : (
              <motion.span
                key="send"
                initial={{ scale: 0, opacity: 0, x: -10, y: 10 }}
                animate={{ scale: 1, opacity: 1, x: 0, y: 0 }}
                exit={{ scale: 0, opacity: 0, x: 10, y: -10 }}
                className="flex items-center justify-center"
              >
                <Send className="size-4 ml-0.5" />
              </motion.span>
            )}
          </AnimatePresence>
          <span className="sr-only">Send message</span>
        </Button>
      </form>
      <div className="text-center mt-3 text-xs text-muted-foreground font-medium">
        Responses are generated by AI and may be inaccurate.
      </div>
    </div>
  )
}
