spring.application.name=PlatformGateway
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

application.base_url = "/api"

application.secret.refresh_token = "refresh_token_secret_key_00000000000000000000000000000000000"
application.secret.access_token = "access_token_secret_key_00000000000000000000000000000000000"
application.expiration.access_token = 300
application.expiration.refresh_token = 604800

spring.web.cors.allowed-origins=http://localhost:5173
