spring.application.name=PlatformGateway
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


application.base_url = "/api"

application.secret.refresh_token = "refresh_token_secret_key_00000000000000000000000000000000000"
application.secret.access_token = "access_token_secret_key_00000000000000000000000000000000000"